spring.application.name=musicapp

#spring.data.mongodb.uri=mongodb://localhost:27017/musicapp
#for production
spring.data.mongodb.uri=mongodb+srv://vijaynatte144_db_user:vijay123@cluster0.tqwrhs8.mongodb.net/music_app?retryWrites=true&w=majority&authSource=admin

#Cloudinary configuration
cloudinary.cloud.name=dk7ko06sw
cloudinary.api-key=194223239842199
cloudinary.api-secret=tH-YIzGfiDDxjRpHFAdI44cWYdQ

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#jwt configuration
jwt.secret=your_jwt_secret_key-is-here-change_this_to_a_secure_key-when-we-deploy-to-production
jwt.expiration=3600000